
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-04
owner: ucsb-cs156-f25
repo_name: team02-f25-04
pull_requests: [{"author":{"id":"U_kgDOCNnsYw","is_bot":false,"login":"anthonywong461","name":"Anthony Wong"},"headRefName":"ucsb_menuitem_table","number":88,"title":"Table Component for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/88"},{"author":{"id":"MDQ6VXNlcjIzNTY0NDU2","is_bot":false,"login":"RyanHung","name":"Ryan Hung"},"headRefName":"rh-add-table-articles","number":87,"title":"RH - added article table + tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/87"},{"author":{"id":"U_kgDODQ5OSw","is_bot":false,"login":"davey-j1","name":""},"headRefName":"xy-UCSBOrganization-table-component","number":85,"title":"Xy ucsb organization table component","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/85"},{"author":{"id":"U_kgDOBtIeXg","is_bot":false,"login":"AJP1012","name":""},"headRefName":"ap-HelpReqeust-create-page","number":84,"title":"ap - Set up Create page for HelpRequest","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/84"},{"author":{"id":"U_kgDOBtIeXg","is_bot":false,"login":"AJP1012","name":""},"headRefName":"ap-HelpRequest-copy-pages-placeholders","number":83,"title":"ap - Created placeholder pages for HelpRequest with basic tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/83"}]
