
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-04
owner: ucsb-cs156-f25
repo_name: team02-f25-04
pull_requests: [{"author":{"id":"U_kgDODQ5OSw","is_bot":false,"login":"davey-j1","name":""},"headRefName":"xy-UCSBOrganization-placeholders","number":92,"title":"Xy ucsb organization placeholders","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/92"},{"author":{"id":"U_kgDOBtIeXg","is_bot":false,"login":"AJP1012","name":""},"headRefName":"ap-HelpRequest-edit-page","number":91,"title":"ap - Set up Edit page for HelpRequest","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/91"},{"author":{"id":"U_kgDOBtIeXg","is_bot":false,"login":"AJP1012","name":""},"headRefName":"ap-HelpRequest-index-page","number":90,"title":"ap - Set up Index page for HelpRequest","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/90"},{"author":{"id":"U_kgDOCM7m8g","is_bot":false,"login":"ChiranArumugam","name":"Chiran Arumugam"},"headRefName":"ca-MenuItemReview-form","number":89,"title":"Ca menu item review form","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/89"},{"author":{"id":"U_kgDOCNnsYw","is_bot":false,"login":"anthonywong461","name":"Anthony Wong"},"headRefName":"ucsb_menuitem_table","number":88,"title":"Table Component for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/88"},{"author":{"id":"U_kgDOBtIeXg","is_bot":false,"login":"AJP1012","name":""},"headRefName":"ap-HelpReqeust-create-page","number":84,"title":"ap - Set up Create page for HelpRequest","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/84"},{"author":{"id":"U_kgDOBtIeXg","is_bot":false,"login":"AJP1012","name":""},"headRefName":"ap-HelpRequest-copy-pages-placeholders","number":83,"title":"ap - Created placeholder pages for HelpRequest with basic tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/83"}]
