
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-04
owner: ucsb-cs156-f25
repo_name: team02-f25-04
pull_requests: [{"author":{"id":"U_kgDOCQ1dXg","is_bot":false,"login":"Max-Changg","name":"Max Chang"},"headRefName":"mc-RecommendationRequest-index-edit","number":108,"title":"Mc recommendation request index edit","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/108"},{"author":{"id":"U_kgDOCQ1dXg","is_bot":false,"login":"Max-Changg","name":"Max Chang"},"headRefName":"mc-RecommendationRequest-create-page","number":107,"title":"Mc recommendation request create page","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/107"},{"author":{"id":"U_kgDOCM7m8g","is_bot":false,"login":"ChiranArumugam","name":"Chiran Arumugam"},"headRefName":"ca-MenuItemReview-index","number":104,"title":"ca - added index page, stories, and corresponding test file","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/104"},{"author":{"id":"U_kgDODQ5OSw","is_bot":false,"login":"davey-j1","name":""},"headRefName":"xy-UCSBOrganization-index-page","number":103,"title":"Xy ucsb organization index page","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/103"},{"author":{"id":"U_kgDOCM7m8g","is_bot":false,"login":"ChiranArumugam","name":"Chiran Arumugam"},"headRefName":"ca-MenuItemReview-create","number":101,"title":"Ca menu item review create page","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/101"},{"author":{"id":"U_kgDODQ5OSw","is_bot":false,"login":"davey-j1","name":""},"headRefName":"xy-UCSBOrganization-create-page","number":93,"title":"Xy ucsb organization create page","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/93"}]
