
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-04
owner: ucsb-cs156-f25
repo_name: team02-f25-04
pull_requests: [{"author":{"id":"U_kgDOBtIeXg","is_bot":false,"login":"AJP1012","name":""},"headRefName":"ap-HelpRequest-e2e-tests","number":128,"title":"ap - Passed HelpRequest E2E tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/128"},{"author":{"id":"U_kgDOCQ1dXg","is_bot":false,"login":"Max-Changg","name":"Max Chang"},"headRefName":"mc-RecommendationRequests-integration-tests","number":126,"title":"mc - added integration tests for recommendation requests controller eâ€¦","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/126"},{"author":{"id":"U_kgDOCM7m8g","is_bot":false,"login":"ChiranArumugam","name":"Chiran Arumugam"},"headRefName":"ca-MenuItemReview-e2e","number":125,"title":"Ca menu item review e2e","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/125"},{"author":{"id":"U_kgDOCNnsYw","is_bot":false,"login":"anthonywong461","name":"Anthony Wong"},"headRefName":"aw-ucsbmenuitem-integration","number":123,"title":"aw - Integration Test for UCSBDiningCommonsMenuItem #114","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/123"}]
