
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-04
owner: ucsb-cs156-f25
repo_name: team02-f25-04
pull_requests: [{"author":{"id":"U_kgDODQ5OSw","is_bot":false,"login":"davey-j1","name":""},"headRefName":"xy-UCSBOrganization-index-page","number":103,"title":"Xy ucsb organization index page","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/103"},{"author":{"id":"MDQ6VXNlcjIzNTY0NDU2","is_bot":false,"login":"RyanHung","name":"Ryan Hung"},"headRefName":"rh-create-page-articles","number":102,"title":"RH - create page articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/102"},{"author":{"id":"U_kgDOCM7m8g","is_bot":false,"login":"ChiranArumugam","name":"Chiran Arumugam"},"headRefName":"ca-MenuItemReview-create","number":101,"title":"Ca menu item review create page","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/101"},{"author":{"id":"U_kgDOCQ1dXg","is_bot":false,"login":"Max-Changg","name":"Max Chang"},"headRefName":"mc-RecommendationRequest-placeholder-pages","number":100,"title":"mc - add placeholder pages for Index, Edit, Create for Recommendationâ€¦","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/100"},{"author":{"id":"U_kgDOBtIeXg","is_bot":false,"login":"AJP1012","name":""},"headRefName":"ap-HelpRequest-edit-page-2","number":96,"title":"ap - Set up Edit Page for HelpRequest","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/96"},{"author":{"id":"U_kgDOCNnsYw","is_bot":false,"login":"anthonywong461","name":"Anthony Wong"},"headRefName":"ucsbMenuItem-placeholder","number":94,"title":"UCSBDiningCommonsMenuItem (Placeholder+)","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/94"},{"author":{"id":"U_kgDODQ5OSw","is_bot":false,"login":"davey-j1","name":""},"headRefName":"xy-UCSBOrganization-create-page","number":93,"title":"Xy ucsb organization create page","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/93"},{"author":{"id":"U_kgDOBtIeXg","is_bot":false,"login":"AJP1012","name":""},"headRefName":"ap-HelpRequest-index-page","number":90,"title":"ap - Set up Index page for HelpRequest","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/90"},{"author":{"id":"U_kgDOBtIeXg","is_bot":false,"login":"AJP1012","name":""},"headRefName":"ap-HelpReqeust-create-page","number":84,"title":"ap - Set up Create page for HelpRequest","url":"https://github.com/ucsb-cs156-f25/team02-f25-04/pull/84"}]
